name: Check Branch Name

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check Out Code
      - name: Check Out Code
        uses: actions/checkout@v3

      # Step 2: Set Node.js Environment (Optional, if not already available)
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Run the JavaScript Validation
      - name: Validate Branch Name
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: node ./.github/workflows/pipelines/validateBranchName.js
