name: Check Branch Name

on:
  # Trigger when a branch is created (excluding main)
  create:
    branches:
      - "*"
      - "!main"

  # Trigger on push events to any branch (excluding main)
  push:
    branches:
      - "*"
      - "!main"

  # Trigger when a pull request is created or updated
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name validation
        run: |
          echo "GitHub Username: ${{ github.actor }}"
          echo "Pull Request Name: ${{ github.event.pull_request.title }}"
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
      - name: PR Name validation
        run: |
          echo "GitHub Username: ${{ github.actor }}"
          echo "Pull Request Name: ${{ github.event.pull_request.title }}"
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
