name: Validate PR Changes in UAT

on:
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    uses: ./.github/workflows/setupNode.yml
    with:
      node_version: '18' # Parameterized Node.js version

  setup-cli:
    needs: setup-node # CLI installation depends on Node.js setup
    uses: ./.github/workflows/setupCli.yml

  validate-branch:
    needs: setup-cli
    runs-on: ubuntu-latest

    steps:
      - name: Debug Working Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -al

      - name: Check SFProject Folder
        run: |
          ls -al ./SFProject/scripts/cicdPipelines/

      - name: Run validateBranchName.js
        run: node ./SFProject/scripts/cicdPipelines/validateBranchName.js
