name: Validate PR Changes in UAT

on:
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    uses: ./.github/workflows/setupNode.yml
    with:
      node_version: '18' # Parameterized Node.js version

  setup-cli:
    needs: setup-node # CLI installation depends on Node.js setup
    uses: ./.github/workflows/setupCli.yml

  validate-delta:
    needs: setup-cli
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full repository checkout

      - name: Debug Repository Structure
        run: |
          echo "Current directory: $(pwd)"
          ls -al
          ls -al SFProject/
          ls -al SFProject/scripts/cicdPipelines/

      - name: Run validateBranchName.js
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: node ./SFProject/scripts/cicdPipelines/validateBranchName.js

